# https://render.com/docs/blueprint-spec
services:
  - type: web
    name: svinolink-bot
    runtime: docker
    plan: free
    autoDeploy: true
    branch: master
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_BASE_URL
        sync: false
      - key: WEBHOOK_PATH
        value: webhook
      - key: PUBLIC_BASE_URL
        sync: false
      - key: YANDEX_API_KEY
        sync: false
      - key: YANDEX_FOLDER_ID
        value: b1g3l4knr91bsq8mqhaq
      - key: SUPABASE_DATABASE_URL
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: INSTAGRAM_COOKIES_FILE
        sync: false
      - key: INSTAGRAM_USERNAME
        sync: false
      - key: INSTAGRAM_PASSWORD
        sync: false
      - key: DOWNLOADS_DIR
        value: /app/downloads
      - key: PORT
        value: "8080"
